server:
  port: 8040
  
spring:
  application:
    name: microservice-gateway-zuul
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
zuul:
# ignored-services: '*'
  routes:
    microservice-consumer-movie: /user/**
